version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/AfrithKhan
file_exists_behaviour: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/AfterInstallHook.sh
      timeout: 300    